server:
  port: 8080

spring:
  application:
    name: bist-daily
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://remotemysql.com:3306/Z63e7BzMKu}
    username: ${MYSQL_USERNAME:Z63e7BzMKu}
    password: ${MYSQL_PASSWORD:aB2cg96P6a}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create